apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-server
    spec:
      containers:
        - name: backend-server
          image: gcr.io/ramen-live/backend-server:v1.1.4tls_healthcheck
          ports:
            - containerPort: 8089
          volumeMounts:
            - name: server-tls
              mountPath: /etc/tls
              readOnly: true
          env:
            - name: DB_URL
              value: mongodb://mongo-svc:27017
            - name: CHANNEL_ID
              value: "1656068485"
      volumes:
        - name: server-tls
          secret:
            secretName: tls-cert
  selector:
    matchLabels:
      app: backend-server
