apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 8088
      port: 80
  loadBalancerIP: "35.194.206.199"
